In [68]:
import pandas as pd
import numpy as np
location = "datasets/kickstartercombo (1).csv"
df = pd.read_csv(location)

In [69]:
df.head()

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
0,0,1000002330,The Songs of Adelaide & Abullah,Publishing,Poetry,GB,failed,1000.0,0.0,GBP,2015-08-11 12:12:00,2015-10-09 11:36:00,0,0.0,NaN,NaN
1,1,1000004038,Where is Hank?,Film & Video,Narrative Film,US,failed,45000.0,220.0,USD,2013-01-12 00:20:00,2013-02-26 00:20:00,3,220.0,NaN,NaN
2,2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,US,failed,5000.0,1.0,USD,2012-03-17 03:24:00,2012-04-16 04:24:00,1,1.0,NaN,NaN
3,3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,US,canceled,19500.0,1283.0,USD,2015-07-04 08:35:00,2015-08-29 01:00:00,14,1283.0,NaN,NaN
4,4,1000014025,Monarch Espresso Bar,Food,Restaurants,US,successful,50000.0,52375.0,USD,2016-02-26 13:38:00,2016-04-01 13:38:00,224,52375.0,NaN,NaN

In [70]:
df.count()

Unnamed: 0          702411
ID                  702411
name                702403
main_category       702411
category            702411
country             702411
state               702411
goal                702411
pledged             702411
currency            702411
launched            702411
deadline            702411
backers             702411
usd pledged         694817
usd_goal_real       378661
usd_pledged_real    378661
dtype: int64

In [71]:
df['main_category'].value_counts()

Film & Video      121331
Music              98710
Publishing         74220
Games              63272
Technology         58730
Design             53979
Art                52177
Food               45844
Fashion            41232
Theater            20888
Photography        20468
Comics             19575
Crafts             16001
Journalism          8838
Dance               7145
Graphic Novels         1
Name: main_category, dtype: int64

In [72]:
df.isnull().sum()

Unnamed: 0               0
ID                       0
name                     8
main_category            0
category                 0
country                  0
state                    0
goal                     0
pledged                  0
currency                 0
launched                 0
deadline                 0
backers                  0
usd pledged           7594
usd_goal_real       323750
usd_pledged_real    323750
dtype: int64

In [73]:
df.sort_values('goal',ascending=True)

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
628239,628239,620302213,LOVELAND Round 6: A Force More Powerful,Art,Conceptual Art,US,successful,1.000000e-02,100.00,USD,2009-11-25 07:54:49,2009-12-04,6,100.000000,1.000000e-02,100.00
260569,260569,620302213,LOVELAND Round 6: A Force More Powerful,Art,Conceptual Art,US,successful,1.000000e-02,100.00,USD,2009-11-25 07:54:00,2009-12-04 07:07:00,6,100.000000,NaN,NaN
641521,641521,688564643,"Word-of-mouth publishing: get ""Corruptions"" ou...",Publishing,Fiction,US,canceled,1.000000e-02,0.00,USD,2011-11-07 16:46:52,2011-12-13,0,0.000000,1.000000e-02,0.00
271909,271909,688564643,"Word-of-mouth publishing: get ""Corruptions"" ou...",Publishing,Fiction,US,canceled,1.000000e-02,0.00,USD,2011-11-07 16:46:00,2011-12-13 16:46:00,0,0.000000,NaN,NaN
316694,316694,9572984,Nana,Film & Video,Shorts,US,failed,1.500000e-01,0.00,USD,2012-01-25 07:23:00,2012-03-16 06:23:00,0,0.000000,NaN,NaN
694151,694151,9572984,Nana,Film & Video,Shorts,US,failed,1.500000e-01,0.00,USD,2012-01-25 07:23:19,2012-03-16,0,0.000000,1.500000e-01,0.00
549921,549921,219760504,RocknRoll NoisePollution,Film & Video,Documentary,US,failed,5.000000e-01,0.00,USD,2011-07-12 15:59:39,2011-07-19,0,0.000000,5.000000e-01,0.00
193585,193585,219760504,RocknRoll NoisePollution,Film & Video,Documentary,US,failed,5.000000e-01,0.00,USD,2011-07-12 15:59:00,2011-07-19 15:59:00,0,0.000000,NaN,NaN
671759,671759,842973116,Updated happy nursery/ lullaby songs (Canceled),Music,Kids,US,canceled,1.000000e+00,0.00,USD,2016-03-17 15:36:53,2016-04-16,0,0.000000,1.000000e+00,0.00
197579,197579,24344396,Potato Salad,Art,Art,US,successful,1.000000e+00,66.00,USD,2014-07-10 18:44:00,2014-07-31 18:44:00,5,66.000000,NaN,NaN
95627,95627,156802730,Ideal Playing Cards Sticker Seals - Black & Go...,Games,Playing Cards,US,failed,1.000000e+00,0.00,USD,2016-01-04 16:41:00,2016-01-05 16:41:00,0,0.000000,NaN,NaN
139775,139775,1830689058,d6xd6 CORE Role-Playing Game,Games,Tabletop Games,US,successful,1.000000e+00,11456.36,USD,2014-07-07 14:53:00,2014-08-03 07:00:00,490,11456.360000,NaN,NaN
573409,573409,339792913,Make Ceri Walk,Film & Video,Experimental,GB,successful,1.000000e+00,10.00,GBP,2014-07-25 17:43:03,2014-08-24,1,17.040000,1.660000e+00,16.58
513391,513391,1965183518,Apple Drawing,Art,Illustration,GB,successful,1.000000e+00,23.28,GBP,2014-12-01 19:44:43,2014-12-31,8,36.430000,1.540000e+00,35.94
204755,204755,286384979,Take a picture,Photography,Photography,US,successful,1.000000e+00,10.00,USD,2014-11-06 08:44:00,2015-01-03 05:59:00,2,10.000000,NaN,NaN
59076,59076,1351052522,Revenge of the IoT Relay - Just an hour to go!,Technology,Gadgets,US,successful,1.000000e+00,6316.00,USD,2015-04-24 20:10:00,2015-04-27 21:00:00,109,6316.000000,NaN,NaN
539077,539077,209708644,SLICE three: FUGUE,Film & Video,Documentary,US,failed,1.000000e+00,0.00,USD,2012-02-14 01:26:18,2012-04-14,0,0.000000,1.000000e+00,0.00
69407,69407,1412689603,"""FULL CIRCLE"" - A Dark Action-Comedy Feature F...",Film & Video,Narrative Film,US,canceled,1.000000e+00,50.00,USD,2011-07-26 21:06:00,2011-08-20 21:06:00,1,50.000000,NaN,NaN
16996,16996,1100301633,Oh Snap! A 'Cards With Text On Them' Game of I...,Games,Tabletop Games,US,successful,1.000000e+00,115.00,USD,2015-04-01 07:00:00,2015-04-08 07:00:00,15,115.000000,NaN,NaN
340642,340642,1085633926,Alexander and the Book of Knowledge (Relaunch),Comics,Comic Books,US,successful,1.000000e+00,2.00,USD,2016-03-29 21:25:10,2016-04-18,2,2.000000,1.000000e+00,2.00
281514,281514,746569507,The fB Project - Mylife Yourlife Ourlife,Art,Digital Art,GB,successful,1.000000e+00,100.00,GBP,2014-03-14 22:32:00,2014-03-24 13:00:00,6,166.250210,NaN,NaN
329602,329602,1030025420,Sounds of New York,Music,Music,US,successful,1.000000e+00,40.00,USD,2015-10-20 23:22:33,2015-10-27,7,40.000000,1.000000e+00,40.00
636022,636022,66066815,SUPER SQUARE CHAOS,Games,Video Games,CA,successful,1.000000e+00,60.00,CAD,2015-04-07 20:57:34,2015-05-08,10,48.080000,8.300000e-01,49.57
599931,599931,475130467,Dice Set Felt Coasters,Games,Gaming Hardware,US,successful,1.000000e+00,7548.00,USD,2016-09-09 18:24:49,2016-10-05,232,1184.000000,1.000000e+00,7548.00
118580,118580,1703892588,Lying to Children,Publishing,Poetry,US,successful,1.000000e+00,38.00,USD,2011-10-30 02:31:00,2011-11-29 03:31:00,8,38.000000,NaN,NaN
263497,263497,638442476,Makenka: studio album + videos and promotion.,Music,Latin,US,successful,1.000000e+00,66.00,USD,2015-01-29 17:31:00,2015-03-16 16:59:00,3,66.000000,NaN,NaN
530127,530127,2051479991,The Hat Man: Shadow Ward,Games,Video Games,US,successful,1.000000e+00,3341.00,USD,2013-12-04 00:16:52,2014-01-03,196,3341.000000,1.000000e+00,3341.00
205605,205605,291858502,Love's Letters - A Shortcut on the Road to Hap...,Publishing,Nonfiction,US,successful,1.000000e+00,393.00,USD,2014-12-10 23:20:00,2015-01-05 21:00:00,14,393.000000,NaN,NaN
599957,599957,475321154,Haiku for You,Publishing,Poetry,US,successful,1.000000e+00,24.00,USD,2016-04-15 19:39:07,2016-05-15,12,24.000000,1.000000e+00,24.00
329401,329401,1028973254,Crap Drawings,Art,Illustration,GB,successful,1.000000e+00,144.05,GBP,2012-11-16 18:55:52,2012-12-16,17,228.260000,1.620000e+00,233.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547112,547112,2137925650,The Time Jumper,Film & Video,Science Fiction,US,canceled,1.000000e+08,0.00,USD,2016-08-11 12:21:47,2016-10-10,0,0.000000,1.000000e+08,0.00
62492,62492,1371612630,Wax Apple,Film & Video,Documentary,US,failed,1.000000e+08,0.00,USD,2014-12-16 15:43:00,2014-12-17 16:00:00,0,0.000000,NaN,NaN
124854,124854,1741515953,Let's prove the earth is FLAT! (Suspended) (Su...,Journalism,Video,US,suspended,1.000000e+08,13.00,USD,2015-12-21 22:29:00,2016-01-20 22:29:00,4,13.000000,NaN,NaN
662242,662242,794141191,Robotech Take Over,Publishing,Fiction,US,failed,1.000000e+08,3577.00,USD,2014-08-01 20:06:07,2014-08-31,27,3577.000000,1.000000e+08,3577.00
191125,191125,2137925650,The Time Jumper,Film & Video,Science Fiction,US,canceled,1.000000e+08,0.00,USD,2016-08-11 12:21:00,2016-10-10 12:21:00,0,0.000000,NaN,NaN
80959,80959,1481016469,Survival SandBox Game (Canceled),Games,Video Games,NO,canceled,1.000000e+08,0.00,NOK,2016-05-10 07:20:00,2016-06-24 07:20:00,0,0.000000,NaN,NaN
208354,208354,308045282,Jesus Priest,Film & Video,Action,CA,failed,1.000000e+08,1.00,CAD,2015-03-05 22:57:00,2015-05-04 18:00:00,1,0.799988,NaN,NaN
691678,691678,944541075,Hydroponic's Skyscraper(un gratte-ciel hydropo...,Technology,Technology,FR,failed,1.000000e+08,2.00,EUR,2015-08-25 23:52:30,2015-10-24,2,2.290000,1.101698e+08,2.20
238380,238380,487345242,Billionaire Boy Blog (Canceled),Publishing,Young Adult,DK,canceled,1.000000e+08,0.00,DKK,2015-02-13 06:45:00,2015-03-15 05:45:00,0,0.000000,NaN,NaN
396740,396740,1371612630,Wax Apple,Film & Video,Documentary,US,failed,1.000000e+08,0.00,USD,2014-12-16 15:43:58,2014-12-17,0,0.000000,1.000000e+08,0.00
135648,135648,1806062709,The Return Of The Bell Witch Movie,Film & Video,Shorts,US,failed,1.000000e+08,1.00,USD,2014-04-09 18:59:00,2014-05-09 18:59:00,1,1.000000,NaN,NaN
240473,240473,499583381,The Scariest Movie Ever Created,Film & Video,Horror,US,failed,1.000000e+08,1.00,USD,2015-07-23 21:44:00,2015-08-22 21:44:00,1,1.000000,NaN,NaN
537090,537090,208731425,Animal - The Bear Life Journey,Art,Painting,US,failed,1.000000e+08,59.00,USD,2017-09-10 17:54:05,2017-11-09,2,0.000000,1.000000e+08,59.00
534776,534776,2075450016,"Virtual Reality Playground in Buffalo, NY",Games,Live Games,US,failed,1.000000e+08,20.00,USD,2015-05-14 02:31:39,2015-06-28,1,20.000000,1.000000e+08,20.00
452585,452585,1654077554,A New Mathematical System,Technology,Technology,NO,failed,1.000000e+08,1950.00,NOK,2017-03-09 00:54:27,2017-03-17,4,0.000000,1.179593e+07,230.02
378759,378759,1279992058,Kybernan Holographic Gaming Network,Games,Video Games,US,failed,1.000000e+08,13.00,USD,2015-11-07 00:57:17,2016-01-01,4,13.000000,1.000000e+08,13.00
549911,549911,219702078,Kitchen from Austria in Switzerland,Food,Restaurants,CH,failed,1.000000e+08,0.00,CHF,2015-08-06 19:12:10,2015-10-05,0,0.000000,1.040572e+08,0.00
297661,297661,843636303,"The Exodus, one Ark or many.",Film & Video,Documentary,US,failed,1.000000e+08,14.00,USD,2016-06-17 17:20:00,2016-08-16 17:20:00,5,0.000000,NaN,NaN
602351,602351,487345242,Billionaire Boy Blog (Canceled),Publishing,Young Adult,DK,canceled,1.000000e+08,0.00,DKK,2015-02-13 06:45:00,2015-03-15,0,0.000000,1.446132e+07,0.00
396525,396525,1370542565,Art Is Fabulous,Art,Art,US,failed,1.000000e+08,115.00,USD,2016-04-06 02:55:07,2016-06-05,2,115.000000,1.000000e+08,115.00
66485,66485,1395179504,Bring back Pontiac,Technology,Technology,US,failed,1.000000e+08,2.00,USD,2016-02-01 13:39:00,2016-04-01 13:39:00,2,2.000000,NaN,NaN
47094,47094,1279992058,Kybernan Holographic Gaming Network,Games,Video Games,US,failed,1.000000e+08,13.00,USD,2015-11-07 00:57:00,2016-01-01 06:59:00,4,13.000000,NaN,NaN
260809,260809,621851828,Kickstarter 2 - We are Making a Better Kicksta...,Publishing,Publishing,US,suspended,1.000000e+08,105.00,USD,2015-09-17 02:45:00,2015-11-16 02:45:00,5,105.000000,NaN,NaN
20151,20151,1119122774,"Help me start a fair media company, Trump Media",Journalism,Video,US,live,1.000000e+08,0.00,USD,2016-11-22 06:41:00,2017-01-21 06:41:00,0,0.000000,NaN,NaN
695228,695228,962949560,"""PG"" Reanimated Cartoons Tha Movie",Film & Video,Animation,US,failed,1.000000e+08,0.00,USD,2015-02-10 23:49:30,2015-04-11,0,0.000000,1.000000e+08,0.00
137250,137250,1815288309,The Book on Comedy 10 GABAGILLTRILLBILLIOPLEXI...,Comics,Comics,US,failed,1.000000e+08,0.00,USD,2014-08-12 21:27:00,2014-10-11 21:27:00,0,0.000000,NaN,NaN
465634,465634,1720842777,NAKED FASHION ART,Art,Illustration,CA,failed,1.000000e+08,0.00,CAD,2015-05-01 19:40:34,2015-06-30,0,0.000000,7.947862e+07,0.00
671889,671889,843636303,"The Exodus, one Ark or many.",Film & Video,Documentary,US,failed,1.000000e+08,14.00,USD,2016-06-17 17:20:52,2016-08-16,5,0.000000,1.000000e+08,14.00
691003,691003,941328479,The Throne : Fall of Lucifer,Film & Video,Movie Theaters,US,failed,1.000000e+08,0.00,USD,2017-08-14 16:45:32,2017-10-13,0,0.000000,1.000000e+08,0.00
347219,347219,1119122774,"Help me start a fair media company, Trump Media",Journalism,Video,US,failed,1.000000e+08,1.00,USD,2016-11-22 06:41:27,2017-01-21,1,0.000000,1.000000e+08,1.00

In [74]:
df.sort_values('currency')

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
154062,154062,1915504176,The Super Furry Festival - A Festival For Animals,Art,Mixed Media,AU,failed,2000.0,200.00,AUD,2014-09-13 06:19:00,2014-10-08 05:18:00,5,181.419390,NaN,NaN
499994,499994,1896509261,"Fervour - TCG, The Dueling Trading Card Game (...",Games,Playing Cards,AU,canceled,6000.0,61.00,AUD,2016-02-23 17:47:33,2016-03-24,3,43.710000,4504.17,45.79
341829,341829,1091679814,Project: Health Stop (Health Food Store),Food,Food,AU,failed,200000.0,3.00,AUD,2016-02-23 00:34:59,2016-04-08,1,2.140000,150591.07,2.26
25898,25898,1153355240,Sundayz Shoes,Fashion,Footwear,AU,failed,25000.0,2370.00,AUD,2015-07-28 02:58:00,2015-09-06 02:58:00,14,1726.017651,NaN,NaN
76511,76511,1454432305,"Pregnancy, art and food = A quirky yet practic...",Art,Painting,AU,failed,12000.0,1139.00,AUD,2014-08-30 15:31:00,2014-10-29 14:31:00,23,1065.413982,NaN,NaN
681652,681652,893200716,"Untitled, fortyseven (47) (Canceled)",Art,Painting,AU,canceled,50000.0,10701.00,AUD,2016-02-29 02:01:17,2016-04-01,46,7625.800000,38402.46,8218.89
402560,402560,1401008008,My Wibberly Wobberly Tooth,Publishing,Children's Books,AU,failed,7995.0,2.00,AUD,2015-02-13 10:55:42,2015-02-27,2,1.530000,6258.81,1.57
601788,601788,484678142,Bounce N Hoops .,Games,Games,AU,failed,7500.0,287.00,AUD,2016-02-04 10:12:20,2016-03-05,11,201.360000,5632.75,215.55
640901,640901,685520092,Rewa Frustum - Where Art meets Purpose,Design,Design,AU,successful,2500.0,2842.00,AUD,2016-06-14 18:07:35,2016-07-15,48,2411.780000,1913.66,2175.44
297815,297815,844549413,Battlefield Royale,Games,Tabletop Games,AU,failed,10000.0,201.00,AUD,2014-10-25 01:43:00,2014-12-24 00:00:00,8,176.129154,NaN,NaN
500003,500003,1896572748,INVENTING THE MESSIAH - a documentary on early...,Film & Video,Documentary,AU,successful,30000.0,30034.69,AUD,2017-02-09 18:57:12,2017-03-26,236,827.790000,22939.29,22965.81
681680,681680,893350596,The Eastwood 'LP1' Vinyl Storage Cabinet,Design,Product Design,AU,failed,14167.0,1952.00,AUD,2016-04-11 09:31:23,2016-05-11,9,1474.270000,10319.78,1421.91
373730,373730,1254730921,DHAGO,Film & Video,Horror,AU,failed,6000.0,0.00,AUD,2014-12-06 23:13:16,2014-12-31,0,0.000000,4868.94,0.00
297825,297825,844615918,BeaReBe.com - Share Economy Online Platform,Technology,Web,AU,failed,8500.0,0.00,AUD,2014-09-09 01:09:00,2014-10-09 01:09:00,0,0.000000,NaN,NaN
681689,681689,893407560,A Matter of Time Kickstarter,Games,Video Games,AU,successful,600.0,1342.50,AUD,2017-07-15 15:29:49,2017-08-19,119,169.500000,474.87,1062.52
601773,601773,484586119,Grey Nomads Magazine (Canceled),Publishing,Periodicals,AU,canceled,2500.0,0.00,AUD,2014-07-06 07:24:29,2014-08-05,0,0.000000,2321.26,0.00
451680,451680,1649320325,The Timestream Drifter,Publishing,Fiction,AU,failed,6000.0,1721.00,AUD,2014-12-21 06:07:55,2015-01-31,15,1401.400000,4713.28,1351.92
164583,164583,1978658222,Australian Made Titanium Drop Bare Survival Tool,Design,Product Design,AU,failed,1500.0,940.00,AUD,2015-09-18 13:13:00,2015-10-18 13:13:00,19,676.448299,NaN,NaN
146654,146654,1871247557,When four hearts wander,Publishing,Fiction,AU,failed,15700.0,8.00,AUD,2015-09-28 23:54:00,2015-11-06 02:00:00,1,5.620602,NaN,NaN
125175,125175,174338697,Swanky socks - The softest socks you will ever...,Fashion,Fashion,AU,failed,25000.0,1404.00,AUD,2014-07-24 00:49:00,2014-09-22 00:49:00,27,1316.734717,NaN,NaN
439699,439699,1588706687,Metal Cast Miniatures (Suspended),Games,Tabletop Games,AU,suspended,400.0,1647.00,AUD,2014-11-26 07:50:59,2014-12-26,33,1412.930000,324.60,1336.53
297814,297814,844542354,WhyTime App - Android Version (Canceled),Technology,Software,AU,canceled,19000.0,617.00,AUD,2014-04-27 12:26:00,2014-05-28 12:26:00,10,572.410379,NaN,NaN
164562,164562,1978524136,TOB Forty Five,Film & Video,Documentary,AU,failed,15000.0,352.00,AUD,2016-03-12 02:38:00,2016-05-11 02:38:00,8,263.313016,NaN,NaN
220523,220523,380157514,Vintage Science Art - Recreating the works of ...,Art,Illustration,AU,successful,500.0,559.00,AUD,2014-06-16 12:19:00,2014-07-16 12:19:00,17,525.583405,NaN,NaN
681587,681587,892923581,AdventureFit Radio,Publishing,Radio & Podcasts,AU,successful,7500.0,7556.00,AUD,2015-12-20 10:02:27,2016-01-19,64,5421.380000,5270.56,5309.91
326166,326166,1012513938,THE NEXT BIG SOCIAL NETWORK - MY PRYME (Can...,Technology,Web,AU,canceled,55000.0,201.00,AUD,2014-08-21 05:16:55,2014-09-20 00:00:00,4,187.670000,48351.65,176.70
584347,584347,395524066,BROKE Streetwear,Fashion,Apparel,AU,failed,1000.0,61.00,AUD,2014-09-25 18:39:49,2014-10-30,2,54.030000,878.97,53.62
220529,220529,38019017,Go Walks,Technology,Apps,AU,failed,2000.0,4.00,AUD,2015-10-22 22:42:00,2015-11-21 22:42:00,1,2.907733,NaN,NaN
373667,373667,1254333765,"After The End- An Open World Retro, Sci-fi RPG",Games,Video Games,AU,failed,5000.0,71.00,AUD,2015-05-23 00:21:17,2015-06-07,8,56.080000,3852.97,54.71
25964,25964,1153723923,Sarah Jane Investigates,Film & Video,Drama,AU,canceled,15000.0,150.00,AUD,2016-11-15 12:01:00,2016-12-15 12:01:00,2,75.490898,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258855,258855,610285287,Raleigh City Farm  An Urban Farm Startup,Food,Food,US,successful,10000.0,15344.50,USD,2012-03-10 11:17:00,2012-04-10 11:00:00,362,15344.500000,NaN,NaN
258856,258856,610285487,Hippoc,Fashion,Fashion,US,failed,10000.0,50.00,USD,2016-04-02 05:23:00,2016-05-01 06:00:00,1,50.000000,NaN,NaN
258857,258857,610293559,Lucky Penny Soaps - Organic and Vegan bath/bea...,Crafts,Crafts,US,failed,1037.0,196.00,USD,2015-10-26 15:56:00,2015-11-25 16:56:00,4,196.000000,NaN,NaN
258858,258858,610295599,"THE MIKE DEODATO, JR. SKETCHBOOK (Ltd. Edition...",Comics,Graphic Novels,US,successful,1500.0,5775.00,USD,2015-10-06 22:12:00,2015-11-20 22:12:00,90,5775.000000,NaN,NaN
258860,258860,610301504,A New Center for Aerial Dance,Dance,Dance,US,successful,8500.0,10605.00,USD,2013-12-02 15:08:00,2014-01-01 06:59:00,166,10605.000000,NaN,NaN
258862,258862,610338449,ARC (Canceled),Film & Video,Animation,US,canceled,4150.0,175.00,USD,2014-03-21 21:19:00,2014-04-20 22:19:00,2,175.000000,NaN,NaN
258863,258863,610338497,The beauty of the Bahamas,Photography,Nature,US,failed,2500.0,0.00,USD,2015-04-26 00:21:00,2015-05-26 00:21:00,0,0.000000,NaN,NaN
258864,258864,61034469,K-9 Cases,Crafts,DIY,US,failed,10000.0,0.00,USD,2015-10-14 20:30:00,2015-11-17 00:00:00,0,0.000000,NaN,NaN
258844,258844,61023238,"""Finish Line"" US & Israel musical collaboration",Music,Pop,US,successful,2000.0,2093.00,USD,2012-02-01 00:30:00,2012-03-02 00:30:00,32,2093.000000,NaN,NaN
258843,258843,610229405,"it's the cookies AND, the message.",Food,Food,US,failed,4300.0,1944.00,USD,2015-01-30 13:13:00,2015-02-24 13:13:00,44,1944.000000,NaN,NaN
258842,258842,610222809,Scott Mulvahill's New Album!,Music,Music,US,successful,7000.0,8040.00,USD,2011-12-27 19:01:00,2012-02-01 05:59:00,112,8040.000000,NaN,NaN
258841,258841,61022247,RLM Entertainment (Klamath Falls Group) music ...,Music,Hip-Hop,US,failed,1800.0,0.00,USD,2015-04-06 19:27:00,2015-04-20 19:27:00,0,0.000000,NaN,NaN
258820,258820,610096150,Bible LA Clothing Co.,Fashion,Apparel,US,failed,10000.0,16.00,USD,2015-03-23 20:13:00,2015-04-22 21:13:00,3,16.000000,NaN,NaN
258821,258821,610103000,Stovetop Scents,Crafts,Crafts,US,failed,8000.0,10.00,USD,2014-01-03 20:39:00,2014-02-02 20:39:00,2,10.000000,NaN,NaN
258823,258823,610122066,JIMNASTICS (Suspended),Dance,Performances,US,suspended,2000.0,100.00,USD,2014-12-13 18:01:00,2015-01-12 18:01:00,2,100.000000,NaN,NaN
258825,258825,610139170,I'M A PRIMARY SOURCE,Publishing,Nonfiction,US,failed,2100.0,275.00,USD,2013-02-20 19:07:00,2013-03-22 18:07:00,5,275.000000,NaN,NaN
258826,258826,61014404,Crucialfest,Music,Rock,US,successful,3000.0,3520.00,USD,2013-05-09 04:44:00,2013-06-11 04:44:00,66,3520.000000,NaN,NaN
258827,258827,610147969,Hospital City by Miranda Huba,Theater,Theater,US,successful,2250.0,2250.00,USD,2011-08-03 21:12:00,2011-09-23 05:00:00,26,2250.000000,NaN,NaN
258828,258828,610148211,"DAS ES GUD, Old World & Country Cuisine W/ Cou...",Food,Restaurants,US,failed,125000.0,9.00,USD,2014-12-02 19:17:00,2015-01-01 19:17:00,1,9.000000,NaN,NaN
258766,258766,609792647,The First Halloween... Nativity Set!! (Canceled),Design,Product Design,US,canceled,16000.0,5826.00,USD,2012-03-26 21:56:00,2012-04-25 21:56:00,89,5826.000000,NaN,NaN
258829,258829,610148845,Red Rose- No Place Like Now Tour 2013,Music,Electronic Music,US,successful,1000.0,1685.00,USD,2013-09-03 19:46:00,2013-10-01 06:55:00,30,1685.000000,NaN,NaN
258831,258831,610157485,2017 Yellowstone National Park Calendar,Publishing,Calendars,US,failed,5000.0,46.00,USD,2015-07-06 18:18:00,2015-08-05 18:18:00,3,46.000000,NaN,NaN
258832,258832,610170717,"Share ""I Am Inanna"" with the world (Canceled)",Publishing,Fiction,US,canceled,3000.0,55.00,USD,2011-06-06 18:16:00,2011-07-06 18:16:00,2,55.000000,NaN,NaN
258833,258833,610175646,Be a Part of Trey Wilson's New Record!,Music,Country & Folk,US,successful,5000.0,7045.00,USD,2013-02-04 15:35:00,2013-03-07 06:59:00,73,7045.000000,NaN,NaN
258835,258835,610191838,Portraying Traditional and Contemporary Japan ...,Art,Digital Art,US,successful,3500.0,3826.00,USD,2013-07-11 20:55:00,2013-08-10 20:55:00,42,3826.000000,NaN,NaN
258836,258836,610197731,Endangered Orphans of Condyle Cove,Games,Tabletop Games,US,successful,4097.0,355970.82,USD,2016-08-22 16:50:00,2016-10-06 16:50:00,7305,14769.130000,NaN,NaN
258837,258837,610215269,Protecting India's Siang River,Technology,Software,US,failed,7500.0,5.00,USD,2010-10-07 21:01:00,2011-01-05 21:01:00,1,5.000000,NaN,NaN
258838,258838,610220923,Bringing back the Dead! Evil Dead the Musical,Theater,Theater,US,failed,999.0,110.00,USD,2012-07-12 22:29:00,2012-08-11 22:29:00,2,110.000000,NaN,NaN
258830,258830,610154753,'MIA 2 LAX' The Track Burnaz Debut EP,Music,Music,"N,""0",successful,2000.0,2452.00,USD,2016-04-08 10:07:00,2016-05-08 10:07:00,0,NaN,NaN,NaN
702410,702410,999988282,Nou Renmen Ayiti! We Love Haiti!,Art,Performance Art,US,failed,2000.0,524.00,USD,2011-07-19 09:07:47,2011-08-16,17,524.000000,2000.00,524.00

In [75]:
df['currency'].value_counts()

USD    556182
GBP     62165
EUR     28972
CAD     27176
AUD     14312
SEK      3090
NZD      2640
DKK      1970
MXN      1966
NOK      1262
CHF      1246
HKD       715
SGD       675
JPY        40
Name: currency, dtype: int64

In [76]:
df.dropna()

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
323750,323750,1000002330,The Songs of Adelaide & Abullah,Publishing,Poetry,GB,failed,1000.0,0.00,GBP,2015-08-11 12:12:28,2015-10-09 00:00:00,0,0.00,1533.95,0.00
323751,323751,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Film & Video,Narrative Film,US,failed,30000.0,2421.00,USD,2017-09-02 04:43:57,2017-11-01 00:00:00,15,100.00,30000.00,2421.00
323752,323752,1000004038,Where is Hank?,Film & Video,Narrative Film,US,failed,45000.0,220.00,USD,2013-01-12 00:20:50,2013-02-26 00:00:00,3,220.00,45000.00,220.00
323753,323753,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,US,failed,5000.0,1.00,USD,2012-03-17 03:24:11,2012-04-16 00:00:00,1,1.00,5000.00,1.00
323754,323754,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,US,canceled,19500.0,1283.00,USD,2015-07-04 08:35:03,2015-08-29 00:00:00,14,1283.00,19500.00,1283.00
323755,323755,1000014025,Monarch Espresso Bar,Food,Restaurants,US,successful,50000.0,52375.00,USD,2016-02-26 13:38:27,2016-04-01 00:00:00,224,52375.00,50000.00,52375.00
323756,323756,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,US,successful,1000.0,1205.00,USD,2014-12-01 18:30:44,2014-12-21 00:00:00,16,1205.00,1000.00,1205.00
323757,323757,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Food,Drinks,US,failed,25000.0,453.00,USD,2016-02-01 20:05:12,2016-03-17 00:00:00,40,453.00,25000.00,453.00
323758,323758,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Design,Product Design,US,canceled,125000.0,8233.00,USD,2014-04-24 18:14:43,2014-05-29 00:00:00,58,8233.00,125000.00,8233.00
323759,323759,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Film & Video,Documentary,US,canceled,65000.0,6240.57,USD,2014-07-11 21:55:48,2014-08-10 00:00:00,43,6240.57,65000.00,6240.57
323760,323760,100004721,Of Jesus and Madmen,Publishing,Nonfiction,CA,failed,2500.0,0.00,CAD,2013-09-09 18:19:37,2013-10-09 00:00:00,0,0.00,2406.39,0.00
323761,323761,100005484,Lisa Lim New CD!,Music,Indie Rock,US,successful,12500.0,12700.00,USD,2013-03-09 06:42:58,2013-04-08 00:00:00,100,12700.00,12500.00,12700.00
323762,323762,1000055792,The Cottage Market,Crafts,Crafts,US,failed,5000.0,0.00,USD,2014-09-02 17:11:50,2014-10-02 00:00:00,0,0.00,5000.00,0.00
323763,323763,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,US,failed,200000.0,0.00,USD,2016-02-09 23:01:12,2016-03-25 00:00:00,0,0.00,200000.00,0.00
323764,323764,1000057089,Tombstone: Old West tabletop game and miniatur...,Games,Tabletop Games,GB,successful,5000.0,94175.00,GBP,2017-04-05 19:44:18,2017-05-03 00:00:00,761,57763.78,6469.73,121857.33
323765,323765,1000064368,Survival Rings,Design,Design,US,failed,2500.0,664.00,USD,2015-01-29 02:10:53,2015-02-28 00:00:00,11,664.00,2500.00,664.00
323766,323766,1000064918,The Beard,Comics,Comic Books,US,failed,1500.0,395.00,USD,2014-10-09 22:27:52,2014-11-08 00:00:00,16,395.00,1500.00,395.00
323767,323767,1000068480,Notes From London: Above & Below,Publishing,Art Books,US,failed,3000.0,789.00,USD,2015-04-10 21:20:54,2015-05-10 00:00:00,20,789.00,3000.00,789.00
323768,323768,1000070642,Mike Corey's Darkness & Light Album,Music,Music,US,successful,250.0,250.00,USD,2012-08-02 14:11:32,2012-08-17 00:00:00,7,250.00,250.00,250.00
323769,323769,1000071625,Boco Tea,Food,Food,US,failed,5000.0,1781.00,USD,2012-05-03 17:24:32,2012-06-02 00:00:00,40,1781.00,5000.00,1781.00
323770,323770,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,US,successful,20000.0,34268.00,USD,2013-11-25 07:06:11,2013-12-30 00:00:00,624,34268.00,20000.00,34268.00
323771,323771,1000081649,MikeyJ clothing brand fundraiser,Fashion,Childrenswear,AU,failed,2500.0,1.00,AUD,2017-08-08 01:20:20,2017-09-07 00:00:00,1,0.00,2026.10,0.81
323772,323772,1000082254,Alice in Wonderland in G Minor,Theater,Theater,US,failed,3500.0,650.00,USD,2014-05-16 10:10:38,2014-06-15 00:00:00,12,650.00,3500.00,650.00
323773,323773,1000087442,Mountain brew: A quest for alcohol sustainability,Food,Drinks,NO,failed,500.0,48.00,NOK,2015-01-26 19:17:33,2015-02-25 00:00:00,3,6.18,65.55,6.29
323774,323774,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,US,successful,175.0,701.66,USD,2014-10-23 17:15:50,2014-11-12 00:00:00,66,701.66,175.00,701.66
323775,323775,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,US,successful,10000.0,15827.00,USD,2010-12-07 23:16:50,2011-01-06 00:00:00,147,15827.00,10000.00,15827.00
323776,323776,1000103948,Superhero Teddy Bear,Crafts,DIY,GB,failed,12000.0,0.00,GBP,2015-12-06 20:09:06,2016-01-05 00:00:00,0,0.00,17489.65,0.00
323777,323777,1000104688,Permaculture Skills,Film & Video,Webseries,CA,successful,17757.0,48905.00,CAD,2014-11-14 18:02:00,2014-12-14 00:00:00,571,43203.25,15313.04,42174.03
323778,323778,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GB,successful,100.0,112.38,GBP,2015-12-29 16:59:29,2016-01-28 00:00:00,27,167.70,142.91,160.60
323779,323779,100011318,My Moon - Animated Short Film,Film & Video,Animation,US,successful,50000.0,57577.31,USD,2017-04-03 17:11:33,2017-05-03 00:00:00,840,10120.00,50000.00,57577.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702381,702381,999832803,MONSTROCARDS- A Creative Drawing Game of Horri...,Games,Playing Cards,US,successful,10000.0,13861.50,USD,2014-09-03 19:53:50,2014-10-03,413,13861.50,10000.00,13861.50
702382,702382,99984851,"""Loreto""",Film & Video,Comedy,US,failed,12000.0,0.00,USD,2014-05-06 23:50:34,2014-06-05,0,0.00,12000.00,0.00
702383,702383,999865831,STATE OF G - Men's Blazer Jacket & Women's Car...,Fashion,Apparel,US,failed,25000.0,11643.00,USD,2014-11-13 17:16:17,2014-12-13,97,11643.00,25000.00,11643.00
702384,702384,999867839,Transcaucasia,Photography,Photography,US,failed,4000.0,3531.00,USD,2010-11-08 02:43:59,2011-01-08,37,3531.00,4000.00,3531.00
702385,702385,99987261,"You're Not Cis, You Just Think You Are: My Enb...",Publishing,Nonfiction,US,failed,800.0,70.00,USD,2015-08-25 22:37:14,2015-09-24,5,70.00,800.00,70.00
702386,702386,999877902,Little Saturday's Debut Album,Music,Country & Folk,CA,successful,5000.0,5435.00,CAD,2014-11-17 17:50:12,2014-12-17,78,4814.88,4311.83,4686.96
702387,702387,999878813,Ways to Look at the Moon,Film & Video,Shorts,US,successful,10000.0,10245.00,USD,2017-08-29 06:57:28,2017-10-13,123,145.00,10000.00,10245.00
702388,702388,999880710,Terminal Uniqueness,Publishing,Nonfiction,US,failed,5000.0,18.00,USD,2014-07-15 02:10:39,2014-08-15,5,18.00,5000.00,18.00
702389,702389,999884445,Superette Tea - Boldly Caffeinated Loose Leaf Tea,Food,Drinks,US,successful,5000.0,5579.00,USD,2015-11-03 13:04:14,2015-12-03,103,5579.00,5000.00,5579.00
702390,702390,999893629,Ciridian Helix (Canceled),Publishing,Fiction,US,canceled,1000.0,100.00,USD,2014-08-08 21:49:31,2014-09-11,2,100.00,1000.00,100.00
702391,702391,99991751,Here is the oasis for the youngest in the world.,Design,Product Design,CH,failed,80000.0,0.00,CHF,2015-07-06 18:00:47,2015-09-04,0,0.00,82207.27,0.00
702392,702392,999929142,ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...,Games,Tabletop Games,FR,successful,1000.0,1246.00,EUR,2017-10-04 11:26:44,2017-10-31,35,66.72,1165.70,1452.47
702393,702393,999931480,Google Glass Shield (Canceled),Technology,3D Printing,US,canceled,6500.0,0.00,USD,2014-05-05 20:22:45,2014-05-26,0,0.00,6500.00,0.00
702394,702394,999934908,The Manual Bar Blade,Design,Product Design,US,successful,3500.0,6169.00,USD,2015-11-23 07:33:14,2015-12-15,120,6169.00,3500.00,6169.00
702395,702395,999941823,The Chronicles of Erinoth - A Graphic Novel,Comics,Comics,GB,failed,16000.0,2738.00,GBP,2013-09-10 22:45:26,2013-10-10,38,4281.15,25566.05,4374.99
702396,702396,999943841,The Dog Coffee Book,Publishing,Children's Books,US,successful,950.0,1732.02,USD,2013-10-18 21:35:04,2013-11-30,31,1732.02,950.00,1732.02
702397,702397,999950812,The Cease is Increase,Publishing,Nonfiction,US,failed,4999.0,980.00,USD,2012-08-15 17:11:00,2012-09-14,16,980.00,4999.00,980.00
702398,702398,999955533,Cards and Chit Network Season 2! (Canceled),Games,Tabletop Games,US,canceled,500.0,121.00,USD,2016-01-24 16:03:27,2016-02-23,5,121.00,500.00,121.00
702399,702399,999963618,Colorado International Activism Film Festival,Film & Video,Narrative Film,US,failed,500.0,135.00,USD,2017-02-08 02:28:44,2017-04-09,6,45.00,500.00,135.00
702400,702400,99996661,Date Seat - Boston iOS App,Technology,Apps,US,failed,6000.0,0.00,USD,2016-07-29 15:36:29,2016-09-05,0,0.00,6000.00,0.00
702401,702401,999969812,AT THE BEACH,Music,Classical Music,CA,successful,5000.0,5501.00,CAD,2014-02-20 01:00:16,2014-03-22,78,5019.92,4529.81,4983.69
702402,702402,999971898,Beach Wrestling Documentary,Film & Video,Documentary,NO,successful,20000.0,21500.00,NOK,2015-03-29 21:30:33,2015-04-28,36,2698.97,2675.19,2875.83
702403,702403,999972264,Islanda,Film & Video,Documentary,US,failed,1700.0,25.00,USD,2012-02-15 04:31:10,2012-03-16,1,25.00,1700.00,25.00
702404,702404,999975836,"Homemade fresh dog food, Cleveland OH",Food,Small Batch,US,failed,6500.0,154.00,USD,2017-03-20 22:08:22,2017-04-19,4,0.00,6500.00,154.00
702405,702405,999976312,Angela's Poetry (Canceled),Publishing,Poetry,CA,canceled,5500.0,0.00,CAD,2014-08-06 03:46:07,2014-09-20,0,0.00,4949.60,0.00
702406,702406,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Film & Video,Documentary,US,canceled,50000.0,25.00,USD,2014-09-17 02:35:30,2014-10-17,1,25.00,50000.00,25.00
702407,702407,999977640,The Tribe,Film & Video,Narrative Film,US,failed,1500.0,155.00,USD,2011-06-22 03:35:14,2011-07-19,5,155.00,1500.00,155.00
702408,702408,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Film & Video,Narrative Film,US,failed,15000.0,20.00,USD,2010-07-01 19:40:30,2010-08-16,1,20.00,15000.00,20.00
702409,702409,999987933,BioDefense Education Kit,Technology,Technology,US,failed,15000.0,200.00,USD,2016-01-13 18:13:53,2016-02-13,6,200.00,15000.00,200.00
702410,702410,999988282,Nou Renmen Ayiti! We Love Haiti!,Art,Performance Art,US,failed,2000.0,524.00,USD,2011-07-19 09:07:47,2011-08-16,17,524.00,2000.00,524.00

In [77]:
df.dropna(axis=1)

,Unnamed: 0,ID,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers
0,0,1000002330,Publishing,Poetry,GB,failed,1000.0,0.00,GBP,2015-08-11 12:12:00,2015-10-09 11:36:00,0
1,1,1000004038,Film & Video,Narrative Film,US,failed,45000.0,220.00,USD,2013-01-12 00:20:00,2013-02-26 00:20:00,3
2,2,1000007540,Music,Music,US,failed,5000.0,1.00,USD,2012-03-17 03:24:00,2012-04-16 04:24:00,1
3,3,1000011046,Film & Video,Film & Video,US,canceled,19500.0,1283.00,USD,2015-07-04 08:35:00,2015-08-29 01:00:00,14
4,4,1000014025,Food,Restaurants,US,successful,50000.0,52375.00,USD,2016-02-26 13:38:00,2016-04-01 13:38:00,224
5,5,1000023410,Food,Food,US,successful,1000.0,1205.00,USD,2014-12-01 18:30:00,2014-12-21 18:30:00,16
6,6,1000030581,Food,Drinks,US,failed,25000.0,453.00,USD,2016-02-01 20:05:00,2016-03-17 19:05:00,40
7,7,1000034518,Design,Product Design,US,canceled,125000.0,8233.00,USD,2014-04-24 18:14:00,2014-05-29 18:14:00,58
8,8,100004195,Film & Video,Documentary,US,canceled,65000.0,6240.57,USD,2014-07-11 21:55:00,2014-08-10 21:55:00,43
9,9,100004721,Publishing,Nonfiction,CA,failed,2500.0,0.00,CAD,2013-09-09 18:19:00,2013-10-09 18:19:00,0
10,10,100005484,Music,Indie Rock,US,successful,12500.0,12700.00,USD,2013-03-09 06:42:00,2013-04-08 06:42:00,100
11,11,1000055792,Crafts,Crafts,US,failed,5000.0,0.00,USD,2014-09-02 17:11:00,2014-10-02 17:11:00,0
12,12,1000056157,Games,Games,US,failed,200000.0,0.00,USD,2016-02-09 23:01:00,2016-03-25 22:01:00,0
13,13,1000064368,Design,Design,US,failed,2500.0,664.00,USD,2015-01-29 02:10:00,2015-02-28 02:10:00,11
14,14,1000064918,Comics,Comic Books,US,failed,1500.0,395.00,USD,2014-10-09 22:27:00,2014-11-08 22:27:00,16
15,15,1000068480,Publishing,Art Books,US,failed,3000.0,789.00,USD,2015-04-10 21:20:00,2015-05-10 21:20:00,20
16,16,1000070642,Music,Music,US,successful,250.0,250.00,USD,2012-08-02 14:11:00,2012-08-17 14:11:00,7
17,17,1000071625,Food,Food,US,failed,5000.0,1781.00,USD,2012-05-03 17:24:00,2012-06-02 17:24:00,40
18,18,1000072011,Fashion,Fashion,US,successful,20000.0,34268.00,USD,2013-11-25 07:06:00,2013-12-30 07:06:00,624
19,19,1000082254,Theater,Theater,US,failed,3500.0,650.00,USD,2014-05-16 10:10:00,2014-06-15 10:09:00,12
20,20,1000087442,Food,Drinks,NO,failed,500.0,48.00,NOK,2015-01-26 19:17:00,2015-02-25 19:17:00,3
21,21,1000091520,Comics,Comics,US,successful,175.0,701.66,USD,2014-10-23 17:15:00,2014-11-12 17:15:00,66
22,22,1000102741,Music,Music,US,successful,10000.0,15827.00,USD,2010-12-07 23:16:00,2011-01-06 23:16:00,147
23,23,1000103948,Crafts,DIY,GB,failed,12000.0,0.00,GBP,2015-12-06 20:09:00,2016-01-05 20:09:00,0
24,24,1000104688,Film & Video,Webseries,CA,successful,17757.0,48905.00,CAD,2014-11-14 18:02:00,2014-12-14 18:02:00,571
25,25,1000104953,Comics,Comics,GB,successful,100.0,112.38,GBP,2015-12-29 16:59:00,2016-01-28 16:59:00,27
26,26,1000115172,Food,Food Trucks,GB,failed,3500.0,21.00,GBP,2015-03-01 18:06:00,2015-03-31 18:06:00,1
27,27,1000117861,Design,Product Design,US,successful,1000.0,47266.00,USD,2016-09-07 13:14:00,2016-10-08 02:00:00,549
28,28,1000120151,Design,Product Design,AU,successful,2000.0,2000.00,AUD,2015-07-23 03:09:00,2015-08-22 03:09:00,18
29,29,1000120287,Art,Public Art,US,failed,25000.0,1395.00,USD,2013-02-12 01:07:00,2013-03-24 00:07:00,30
...,...,...,...,...,...,...,...,...,...,...,...,...
702381,702381,999832803,Games,Playing Cards,US,successful,10000.0,13861.50,USD,2014-09-03 19:53:50,2014-10-03,413
702382,702382,99984851,Film & Video,Comedy,US,failed,12000.0,0.00,USD,2014-05-06 23:50:34,2014-06-05,0
702383,702383,999865831,Fashion,Apparel,US,failed,25000.0,11643.00,USD,2014-11-13 17:16:17,2014-12-13,97
702384,702384,999867839,Photography,Photography,US,failed,4000.0,3531.00,USD,2010-11-08 02:43:59,2011-01-08,37
702385,702385,99987261,Publishing,Nonfiction,US,failed,800.0,70.00,USD,2015-08-25 22:37:14,2015-09-24,5
702386,702386,999877902,Music,Country & Folk,CA,successful,5000.0,5435.00,CAD,2014-11-17 17:50:12,2014-12-17,78
702387,702387,999878813,Film & Video,Shorts,US,successful,10000.0,10245.00,USD,2017-08-29 06:57:28,2017-10-13,123
702388,702388,999880710,Publishing,Nonfiction,US,failed,5000.0,18.00,USD,2014-07-15 02:10:39,2014-08-15,5
702389,702389,999884445,Food,Drinks,US,successful,5000.0,5579.00,USD,2015-11-03 13:04:14,2015-12-03,103
702390,702390,999893629,Publishing,Fiction,US,canceled,1000.0,100.00,USD,2014-08-08 21:49:31,2014-09-11,2
702391,702391,99991751,Design,Product Design,CH,failed,80000.0,0.00,CHF,2015-07-06 18:00:47,2015-09-04,0
702392,702392,999929142,Games,Tabletop Games,FR,successful,1000.0,1246.00,EUR,2017-10-04 11:26:44,2017-10-31,35
702393,702393,999931480,Technology,3D Printing,US,canceled,6500.0,0.00,USD,2014-05-05 20:22:45,2014-05-26,0
702394,702394,999934908,Design,Product Design,US,successful,3500.0,6169.00,USD,2015-11-23 07:33:14,2015-12-15,120
702395,702395,999941823,Comics,Comics,GB,failed,16000.0,2738.00,GBP,2013-09-10 22:45:26,2013-10-10,38
702396,702396,999943841,Publishing,Children's Books,US,successful,950.0,1732.02,USD,2013-10-18 21:35:04,2013-11-30,31
702397,702397,999950812,Publishing,Nonfiction,US,failed,4999.0,980.00,USD,2012-08-15 17:11:00,2012-09-14,16
702398,702398,999955533,Games,Tabletop Games,US,canceled,500.0,121.00,USD,2016-01-24 16:03:27,2016-02-23,5
702399,702399,999963618,Film & Video,Narrative Film,US,failed,500.0,135.00,USD,2017-02-08 02:28:44,2017-04-09,6
702400,702400,99996661,Technology,Apps,US,failed,6000.0,0.00,USD,2016-07-29 15:36:29,2016-09-05,0
702401,702401,999969812,Music,Classical Music,CA,successful,5000.0,5501.00,CAD,2014-02-20 01:00:16,2014-03-22,78
702402,702402,999971898,Film & Video,Documentary,NO,successful,20000.0,21500.00,NOK,2015-03-29 21:30:33,2015-04-28,36
702403,702403,999972264,Film & Video,Documentary,US,failed,1700.0,25.00,USD,2012-02-15 04:31:10,2012-03-16,1
702404,702404,999975836,Food,Small Batch,US,failed,6500.0,154.00,USD,2017-03-20 22:08:22,2017-04-19,4
702405,702405,999976312,Publishing,Poetry,CA,canceled,5500.0,0.00,CAD,2014-08-06 03:46:07,2014-09-20,0
702406,702406,999976400,Film & Video,Documentary,US,canceled,50000.0,25.00,USD,2014-09-17 02:35:30,2014-10-17,1
702407,702407,999977640,Film & Video,Narrative Film,US,failed,1500.0,155.00,USD,2011-06-22 03:35:14,2011-07-19,5
702408,702408,999986353,Film & Video,Narrative Film,US,failed,15000.0,20.00,USD,2010-07-01 19:40:30,2010-08-16,1
702409,702409,999987933,Technology,Technology,US,failed,15000.0,200.00,USD,2016-01-13 18:13:53,2016-02-13,6
702410,702410,999988282,Art,Performance Art,US,failed,2000.0,524.00,USD,2011-07-19 09:07:47,2011-08-16,17

In [91]:
df.sort_values(by='usd_goal_real'ascending=False)
df.sort_values(by='backers'ascending=False)
df.sort_values(by='state', ascending=False)

SyntaxError: invalid syntax (<ipython-input-91-70af27ebe823>, line 1)

In [112]:
df.sort_values(['main_category'])

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
702410,702410,999988282,Nou Renmen Ayiti! We Love Haiti!,Art,Performance Art,US,failed,2000.0,524.00,USD,2011-07-19 09:07:47,2011-08-16,17,524.000000,2000.00,524.00
84346,84346,1500430001,It's Clay Time with Helenske Clayworks,Art,Ceramics,US,successful,18000.0,19000.00,USD,2016-03-30 17:47:00,2016-04-29 17:47:00,124,19000.000000,NaN,NaN
633108,633108,645789799,Positively Postal Art Exhibition,Art,Mixed Media,GB,failed,12000.0,25.00,GBP,2013-08-12 22:36:20,2013-09-16,4,38.770000,19223.38,40.05
282329,282329,751531671,ENTHEON: The Alex Grey Visionary Art Experience,Art,Painting,US,successful,125000.0,210127.69,USD,2013-04-25 07:55:00,2013-06-01 05:59:00,1510,210127.690000,NaN,NaN
282340,282340,75156034,"Open an Art and Culture Center in Gardner, Mas...",Art,Art,US,failed,275000.0,0.00,USD,2010-11-15 16:26:00,2010-12-15 16:26:00,0,0.000000,NaN,NaN
84330,84330,1500365185,Love and Madness at Rokeby Mansion,Art,Performance Art,US,successful,500.0,855.00,USD,2011-10-14 05:24:00,2011-11-11 05:59:00,27,855.000000,NaN,NaN
84326,84326,1500356897,Graphic Designs from A Poet's Expression,Art,Digital Art,US,failed,60.0,0.00,USD,2014-08-19 04:00:00,2014-10-18 03:32:00,0,0.000000,NaN,NaN
471671,471671,1751751341,Bienveillance Jewelry Business Startup,Art,Art,US,failed,4000.0,0.00,USD,2016-02-01 22:34:31,2016-03-02,0,0.000000,4000.00,0.00
282359,282359,751658237,professional hand castings of your loved ones.,Art,Art,US,failed,5000.0,0.00,USD,2016-04-06 23:58:00,2016-05-06 23:58:00,0,0.000000,NaN,NaN
84315,84315,1500319810,The Van Camera Obscura in Lebanon (Canceled),Art,Public Art,US,canceled,7000.0,1344.00,USD,2015-08-15 00:15:00,2015-09-08 00:15:00,19,1344.000000,NaN,NaN
84311,84311,150030257,Punny Labor Day Greeting Cards,Art,Digital Art,US,failed,500.0,64.00,USD,2013-08-23 01:03:00,2013-08-28 01:03:00,6,64.000000,NaN,NaN
471656,471656,1751662151,the alternate realities of chef thom,Art,Art,US,failed,1000.0,0.00,USD,2015-03-10 18:43:51,2015-04-09,0,0.000000,1000.00,0.00
471648,471648,1751639087,Trek: A Photographic Adventure Book for Your C...,Art,Digital Art,US,successful,500.0,610.00,USD,2015-07-27 16:27:37,2015-08-28,12,610.000000,500.00,610.00
471641,471641,1751614050,71 POP: Detroit Pop-Up Shop for Emerging Artis...,Art,Art,US,canceled,30000.0,610.00,USD,2011-03-23 02:28:56,2011-05-16,15,610.000000,30000.00,610.00
471633,471633,1751581426,American Messiah sculpture,Art,Sculpture,US,failed,9500.0,554.00,USD,2014-11-05 15:35:14,2014-12-05,16,554.000000,9500.00,554.00
282399,282399,751854304,IDENTITY/MEMORY,Art,Art,GB,successful,3000.0,3941.00,GBP,2014-11-22 20:46:00,2014-12-22 20:46:00,35,6188.270400,NaN,NaN
633107,633107,6457893,Funding for Chicago's 2014 ART FAIRS,Art,Art,US,failed,2000.0,350.00,USD,2014-02-19 18:45:32,2014-03-21,7,350.000000,2000.00,350.00
282325,282325,751523887,Station16: A global street art story,Art,Art,CA,successful,20000.0,23057.00,CAD,2013-11-27 18:33:00,2013-12-27 18:33:00,137,21874.570170,NaN,NaN
84350,84350,1500457543,Red Dragonfly Project - Art Therapy for Homici...,Art,Painting,US,failed,1000.0,71.00,USD,2014-08-28 02:47:00,2014-09-24 02:47:00,5,71.000000,NaN,NaN
282309,282309,751420667,As 1 Gallery ~ A $5 Contribution Campaign,Art,Art,US,successful,2000.0,2240.00,USD,2014-05-01 21:31:00,2014-05-14 04:00:00,139,2240.000000,NaN,NaN
282251,282251,751076272,"ROSHANAI (""Illuminate"") for Burning Man 2016",Art,Public Art,US,successful,20000.0,21272.00,USD,2016-06-30 02:31:00,2016-08-01 09:00:00,250,3759.000000,NaN,NaN
84391,84391,1500704573,The Moment,Art,Art,US,successful,300.0,475.00,USD,2012-03-20 17:27:00,2012-04-14 18:27:00,7,475.000000,NaN,NaN
471733,471733,1752097539,Ligeti Lines Collaboration: Music-Art-Dance,Art,Performance Art,US,successful,5000.0,5050.00,USD,2015-08-08 18:18:54,2015-09-07,35,5050.000000,5000.00,5050.00
282275,282275,751273320,Cards for Smiles,Art,Art,GB,successful,1000.0,1103.00,GBP,2016-03-15 12:04:00,2016-04-14 13:04:00,50,1586.561840,NaN,NaN
471723,471723,175204899,Raise a Stage for the FAB! Festival,Art,Public Art,US,successful,3000.0,3447.00,USD,2013-08-26 16:34:13,2013-09-26,75,3447.000000,3000.00,3447.00
633082,633082,645657720,The straw cube - a crowd-sourced work of art. ...,Art,Public Art,GB,canceled,1340.0,0.00,GBP,2014-01-28 20:17:06,2014-02-27,0,0.000000,2240.17,0.00
633084,633084,645667188,Rasa Performance Project (Canceled),Art,Performance Art,US,canceled,1500.0,255.00,USD,2012-09-18 02:55:41,2012-10-12,7,255.000000,1500.00,255.00
471629,471629,1751538487,"Things that Stick, Stickers by Jason Sorrell",Art,Illustration,US,failed,2000.0,219.00,USD,2016-04-08 00:22:08,2016-05-08,13,219.000000,2000.00,219.00
282287,282287,751319901,Night of the Living Dead at The Overtime,Art,Performance Art,US,successful,1500.0,2701.00,USD,2013-08-27 19:39:00,2013-09-26 19:39:00,43,2701.000000,NaN,NaN
282299,282299,751362178,Castles of the Seven Kingdoms: Painting a Game...,Art,Illustration,US,successful,1500.0,1987.00,USD,2011-09-29 10:56:00,2011-11-13 10:56:00,66,1987.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400750,400750,1391723768,The Tempest Ladies go to APAP,Theater,Theater,US,successful,1500.0,1550.00,USD,2010-11-18 09:37:58,2010-12-18,14,1550.000000,1500.00,1550.00
277504,277504,722109946,SPEAKEASY - a new musical,Theater,Musical,US,successful,13500.0,14305.00,USD,2015-11-16 15:50:00,2015-12-22 19:00:00,142,14305.000000,NaN,NaN
337827,337827,1070776085,"A New Global, Universal Vision of Life on this...",Theater,Theater,US,failed,9625.0,411.00,USD,2014-01-15 18:37:04,2014-02-14,13,411.000000,9625.00,411.00
626205,626205,610220923,Bringing back the Dead! Evil Dead the Musical,Theater,Theater,US,failed,999.0,110.00,USD,2012-07-12 22:29:40,2012-08-11,2,110.000000,999.00,110.00
32821,32821,1194638053,Help DORO & DIEGA find their way to the Orland...,Theater,Musical,US,successful,1200.0,1547.00,USD,2016-02-20 04:22:00,2016-03-15 17:00:00,24,1547.000000,NaN,NaN
277497,277497,722093744,"ULYSSES, a play based on the James Joyce novel",Theater,Theater,US,successful,5000.0,5074.00,USD,2012-01-31 03:07:00,2012-03-16 02:07:00,85,5074.000000,NaN,NaN
582714,582714,387056652,A CLASSY EVENING WITH LADY JESAIRA,Theater,Theater,US,failed,7000.0,542.00,USD,2012-09-04 05:47:24,2012-11-03,17,542.000000,7000.00,542.00
626217,626217,61026619,"Almost, Maine - A FREEKS Theater Production",Theater,Theater,US,successful,1500.0,1500.00,USD,2014-02-28 09:29:53,2014-03-10,12,1500.000000,1500.00,1500.00
259545,259545,614423772,Hootenanny Productions Presents The Mad Dog Blues,Theater,Theater,US,successful,1200.0,1500.00,USD,2011-06-13 16:43:00,2011-07-03 16:43:00,29,1500.000000,NaN,NaN
337784,337784,1070575976,In This Economy - Capital Fringe Festival 2012,Theater,Theater,US,successful,1200.0,2486.00,USD,2012-05-03 16:58:25,2012-07-02,61,2486.000000,1200.00,2486.00
369237,369237,1231098789,Voice 4 Vision Puppet Festival,Theater,Theater,US,successful,2000.0,2030.00,USD,2011-10-19 17:39:16,2011-11-30,41,2030.000000,2000.00,2030.00
225838,225838,411894285,"Self-publish a 98-year-old drummer's memoir, ""...",Theater,Theater,US,successful,700.0,920.00,USD,2014-05-05 21:15:00,2014-06-04 21:15:00,18,920.000000,NaN,NaN
199462,199462,254687645,L.A. TOOL AND DIE: LIVE! (A Pre-Condom Comedy!...,Theater,Theater,US,successful,2500.0,3000.00,USD,2010-05-04 18:20:00,2010-06-26 05:59:00,55,3000.000000,NaN,NaN
675450,675450,861690146,"'Seven Crazy Bitches '- Assembly Rooms, Edinburgh",Theater,Comedy,GB,successful,1500.0,2028.00,GBP,2017-06-13 10:32:33,2017-07-13,79,225.840000,1946.11,2631.14
337790,337790,1070586108,New Play 'Miss Valentine' Charms NYC!,Theater,Theater,US,successful,5000.0,5470.00,USD,2013-02-06 15:54:02,2013-03-08,49,5470.000000,5000.00,5470.00
517875,517875,1988249074,The Scottsboro Boys (Canceled),Theater,Musical,GB,canceled,50000.0,26949.00,GBP,2014-08-23 11:32:40,2014-10-03,33,44676.130000,80331.61,43297.13
32847,32847,1194858431,Irish Premier of Craig Adams' LIFT at the MAC ...,Theater,Theater,GB,failed,3500.0,75.00,GBP,2014-04-10 19:15:00,2014-06-09 19:15:00,5,125.590484,NaN,NaN
675437,675437,861616611,"ArreuG, a performance searching for wings to P...",Theater,Festivals,MX,successful,50000.0,50000.00,MXN,2016-12-28 06:04:43,2017-01-27,24,167.170000,2368.77,2368.77
626250,626250,610422200,Support the 'From Page To Season' of new music...,Theater,Theater,GB,successful,2500.0,2723.00,GBP,2013-12-20 19:54:27,2014-02-03,74,4458.050000,4081.70,4445.79
92885,92885,1552195105,Happy Karaoke Fun Time Goes Off-Broadway!,Theater,Musical,US,successful,5000.0,6374.00,USD,2014-08-21 13:41:00,2014-09-12 13:41:00,119,6374.000000,NaN,NaN
92878,92878,1552108265,The Barbican Photography Trip 2015,Theater,Plays,AU,failed,30000.0,0.00,AUD,2014-07-09 09:48:00,2014-09-07 09:48:00,0,0.000000,NaN,NaN
426394,426394,1521564818,"BROWNSTAR in...""FASTER THAN THE SPEED OF WHITE""",Theater,Theater,US,successful,2000.0,2261.00,USD,2010-07-30 05:57:12,2010-08-20,42,2261.000000,2000.00,2261.00
294093,294093,821947701,spacestation1985,Theater,Theater,US,successful,5000.0,5150.95,USD,2012-08-21 17:28:00,2012-09-13 19:00:00,110,5150.950000,NaN,NaN
449038,449038,1636097945,Urban Tanuki Samurai,Theater,Theater,US,successful,700.0,785.00,USD,2011-12-16 01:17:15,2012-01-16,23,785.000000,700.00,785.00
32874,32874,1194996784,Songs From My Red suitcase - A One-Woman Mus...,Theater,Theater,US,failed,3000.0,325.00,USD,2013-01-16 02:08:00,2013-02-12 07:00:00,7,325.000000,NaN,NaN
269101,269101,671692295,Act Out After School Theater,Theater,Theater,US,failed,5000.0,1325.00,USD,2013-07-31 17:50:00,2013-08-30 17:50:00,16,1325.000000,NaN,NaN
282480,282480,752276394,"British pub theatre in Philly: 'a Play, a Pie ...",Theater,Theater,US,successful,5000.0,5006.00,USD,2011-07-20 05:02:00,2011-09-03 05:02:00,39,5006.000000,NaN,NaN
92859,92859,1551975360,London theatre company to take Ophelia to Poland,Theater,Theater,GB,successful,1000.0,1085.00,GBP,2013-04-19 09:26:00,2013-05-19 09:26:00,19,1654.621734,NaN,NaN
277501,277501,722105264,Free Desiree is going to the New York Fringe F...,Theater,Theater,US,successful,3000.0,3000.00,USD,2013-06-29 21:57:00,2013-07-31 06:00:00,33,3000.000000,NaN,NaN
649973,649973,731481438,Puppetry for Orphans and Refugees in Jordan,Theater,Theater,US,failed,3000.0,20.00,USD,2009-09-06 20:53:30,2009-12-04,2,20.000000,3000.00,20.00

In [ ]:
df.drop_duplicates('failed',)

df.sort_values('Main_category

In [121]:
df['main_category=art'] = pd.Categorical(df['Music'])
df

KeyError: 'Music'